In [1]:
#This is to add Gaussian noise to the original hateful_memes images
#The new dataset with noise will be incorporated to "img" folder & "tain.jsonl" file of the original hateful_memes dataset used during fine-tuning

In [1]:
import pandas as pd
import numpy as np
import os
import augly.text as textaugs
import random

In [2]:
initial_train=pd.read_json("C:\\Users\\yshen\\Documents\\Georgia Tech\\4\\Deep Learning\\pp_textadd\\hateful_memes\\train.jsonl",lines=True)

In [3]:
initial_train.head()

,id,img,label,text
0,42953,img/42953.png,0,its their character not their color that matters
1,23058,img/23058.png,0,don't be afraid to love again everyone is not ...
2,13894,img/13894.png,0,putting bows on your pet
3,37408,img/37408.png,0,i love everything and everybody! except for sq...
4,82403,img/82403.png,0,"everybody loves chocolate chip cookies, even h..."

In [4]:
initial_train[(initial_train['label']==1)]

,id,img,label,text
7,70914,img/70914.png,1,tattoos are bad for your health i know 5 milli...
10,79351,img/79351.png,1,jew mad? get fuhrerious!
12,25489,img/25489.png,1,brother... a day without a blast is a day wasted
23,97180,img/97180.png,1,if there is no race it can't be homicide
26,15872,img/15872.png,1,when you come home from a long day of suicide ...
...,...,...,...,...
12742,12837,img/12837.png,1,iḿaǤine iᚩ yØu ₩ill a gᶉoup Ọf peoplĚ sǿ diకgu...
12743,30168,img/30168.png,1,"hĭ, i 'm natℯ i' m a l£sbiaⓃ iℵ recÕverႸ"
12745,82163,img/82163.png,1,please maќe thⒺm whîte
12746,9572,img/09572.png,1,"alŀ mℯn Åre ₳nîmals baby, somỂ jԱst mäke bҿtte..."
12748,85096,img/85096.png,1,re₥embeŖ no fαggot

In [7]:
num_alter=len(initial_train)
l=random.sample(range(0, num_alter), num_alter//2)

In [38]:
aug=textaugs.ReplaceSimilarUnicodeChars(aug_word_p=0.8)

In [39]:
for i in l:
    
    meta=[]
    t=aug(initial_train['text'][i], metadata=meta)
    
    df= pd.DataFrame([[initial_train['id'][i],initial_train['img'][i],initial_train['label'][i],t]],columns=['id','img','label','text'])
    
    initial_train=initial_train.append(df,ignore_index=True)

In [40]:
initial_train.head()

,id,img,label,text
0,42953,img/42953.png,0,its their character not their color that matters
1,23058,img/23058.png,0,don't be afraid to love again everyone is not ...
2,13894,img/13894.png,0,putting bows on your pet
3,37408,img/37408.png,0,i love everything and everybody! except for sq...
4,82403,img/82403.png,0,"everybody loves chocolate chip cookies, even h..."

In [41]:
initial_train.shape

(12750, 4)

In [42]:
initial_train.tail()

,id,img,label,text
12745,82163,img/82163.png,1,please maќe thⒺm whîte
12746,9572,img/09572.png,1,"alŀ mℯn Åre ₳nîmals baby, somỂ jԱst mäke bҿtte..."
12747,98504,img/98504.png,0,hahǻha gÒod onÈ ḽet' s bนrn 6 ᛖilȴion tỜ ceⓛeb...
12748,85096,img/85096.png,1,re₥embeŖ no fαggot
12749,7431,img/07431.png,0,leȺve nΘ dog behĭnd

In [42]:
# aug=textaugs.ReplaceSimilarUnicodeChars(aug_word_p=0.6)

In [43]:
# t=aug(input_text, metadata=meta)

In [43]:
initial_train.to_json('C:\\Users\\yshen\\Documents\\Georgia Tech\\4\\Deep Learning\\pp_textadd\\train.jsonl', orient='records', lines=True)